project:
  type: website

website:
  title: "Test Utterances"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    comments:
      utterances:
        repo: r-leyshon/quarto-utterances
