project:
  type: website
  output-dir: docs

website:
  title: "Test Utterances"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    comments:
      utterances:
        repo: r-leyshon/quarto-utterances
        label: "utterance" # optional
        theme: icy-dark # optional
        issue-term: url